In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("titanic (1).csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

####Columns in Titanic Dataset
Column
Meaning
PassengerId
Unique passenger ID
Survived
Target variable (0 = died, 1 = survived)
Pclass
Ticket class
Name
Passenger name
Sex
Male / Female
Age
Passenger age
SibSp
Number of siblings/spouse
Parch
Number of parents/children
Ticket
Ticket number
Fare
Ticket price
Cabin
Cabin number
Embarked
Port of embarkation

#####Description
In this project, I worked on the Titanic dataset to predict whether a passenger survived or not. The dataset contains information about passengers such as age, gender, ticket class, fare, and embarkation port.
First, I imported the Pandas library to handle and analyze the data. Then I loaded the dataset using pd.read_csv() which reads the CSV file and converts it into a DataFrame structure for easier analysis.
The dataset contains 891 rows and 12 columns, representing different passenger features. Displaying the dataset helps us understand the structure, columns, and types of data before starting data cleaning and preprocessing.

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [4]:
df.describe().sum()

PassengerId    3824.353842
Survived        893.870431
Pclass          906.144713
Age             924.770615
SibSp           901.625751
Parch           898.187651
Fare           1538.591437
dtype: float64

In [5]:
# fill missing Age values with mean
df['Age'] = df['Age'].fillna(df['Age'].mean())

# drop Cabin column
df.drop('Cabin', axis=1, inplace=True)

# drop rows where Embarked is missing
df.dropna(subset=['Embarked'], inplace=True)

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  889 non-null    int64
 1   Survived     889 non-null    int64
 2   Pclass       889 non-null    int64
 3   Name         889 non-null    object
 4   Sex          889 non-null    object
 5   Age          889 non-null    float64
 6   SibSp        889 non-null    int64
 7   Parch        889 non-null    int64
 8   Ticket       889 non-null    object
 9   Fare         889 non-null    float64
 10  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 83.3+ KB

####Checking the Cleaned Dataset
After handling the missing values, I checked the dataset structure using df.info(). This step helps verify that the missing values in the Age and Embarked columns have been handled and that the Cabin column has been removed. It also shows the total number of rows, columns, and the data types of each feature.

In [6]:
df['Age'].fillna(df['Age'].mean())

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 889, dtype: float64

In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Sex'] = le.fit_transform(df['Sex'])
df['Embarked'] = le.fit_transform(df['Embarked'])

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,0
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,2
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,2

####Encoding Categorical Variables
In this step, I converted categorical variables into numerical values using Label Encoding. The dataset contains text values in columns such as Sex and Embarked, which machine learning models cannot process directly. Therefore, I used the LabelEncoder from the sklearn library to transform these categorical values into numerical form. This prepares the dataset for building a machine learning model.

In [8]:
X = df.drop('Survived', axis=1)
y = df['Survived']

X.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,2
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,0
2,3,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,2
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,2
4,5,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,2

####For the step shown in your screenshot (X = df.drop('Survived', axis=1) and y = df['Survived']), write this Markdown explanation:
Feature Selection
In this step, I separated the dataset into features and target variables. The Survived column is the target variable because it represents whether a passenger survived or not. All the remaining columns are used as input features for the machine learning model. This separation is necessary before splitting the data into training and testing sets.

In [9]:
df.drop('Survived', axis=1)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,3,"Braund, Mr. Owen Harris",1,22.000000,1,0,A/5 21171,7.2500,2
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.000000,1,0,PC 17599,71.2833,0
2,3,3,"Heikkinen, Miss. Laina",0,26.000000,0,0,STON/O2. 3101282,7.9250,2
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.000000,1,0,113803,53.1000,2
4,5,3,"Allen, Mr. William Henry",1,35.000000,0,0,373450,8.0500,2
...,...,...,...,...,...,...,...,...,...,...
886,887,2,"Montvila, Rev. Juozas",1,27.000000,0,0,211536,13.0000,2
887,888,1,"Graham, Miss. Margaret Edith",0,19.000000,0,0,112053,30.0000,2
888,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",0,29.699118,1,2,W./C. 6607,23.4500,2
889,890,1,"Behr, Mr. Karl Howell",1,26.000000,0,0,111369,30.0000,0
890,891,3,"Dooley, Mr. Patrick",1,32.000000,0,0,370376,7.7500,1

In [10]:
y = df['Survived']

In [11]:
X = df.drop(['Survived','Name','Ticket','PassengerId'], axis=1)
y = df['Survived']

X.head()

   Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       3    1  22.0      1      0   7.2500         2
1       1    0  38.0      1      0  71.2833         0
2       3    0  26.0      0      0   7.9250         2
3       1    0  35.0      1      0  53.1000         2
4       3    1  35.0      0      0   8.0500         2

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [13]:
print(X_train.shape)
print(X_test.shape)

(711, 7)
(178, 7)

####Train-Test Split
In this step, I divided the dataset into training and testing sets using the train_test_split function from sklearn. The training data is used to train the machine learning model, while the testing data is used to evaluate its performance on unseen data. I used 80% of the data for training and 20% for testing.

In [14]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

In [15]:
y_pred = model.predict(X_test)

In [16]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.7808988764044944

###Logistic Regression Model
In this step, I applied the Logistic Regression algorithm to build a classification model. The model was trained using the training dataset (X_train and y_train). Logistic Regression is suitable for this problem because the target variable Survived is binary (0 = did not survive, 1 = survived).
Model Prediction and Accuracy
After training the model, I used it to predict the survival of passengers in the test dataset using model.predict(). I then evaluated the model performance using accuracy score, which measures the percentage of correct predictions made by the model. The model achieved an accuracy of approximately 78%.

In [19]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier()

dt_model.fit(X_train, y_train)

DecisionTreeClassifier()

In [20]:
y_pred_dt = dt_model.predict(X_test)

In [21]:
from sklearn.metrics import accuracy_score

print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))

Decision Tree Accuracy: 0.7528089887640449

####Decision Tree Model
In this step, I used the Decision Tree Classifier to build another classification model for predicting passenger survival. The model was trained using the training dataset (X_train and y_train). Decision Trees work by splitting the data into branches based on feature values to make predictions.
Model Evaluation
After training the Decision Tree model, I used it to predict the survival outcome for the test dataset using predict(). The model performance was evaluated using the accuracy score, which compares predicted values with actual values. The Decision Tree model achieved an accuracy of approximately 74%.

In [22]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

KNeighborsClassifier()

In [23]:
y_pred_knn = knn.predict(X_test)

print("KNN Accuracy:", accuracy_score(y_test, y_pred_knn))

KNN Accuracy: 0.7078651685393258

####K-Nearest Neighbors (KNN) Model
In this step, I applied the K-Nearest Neighbors (KNN) algorithm to build another classification model. KNN works by identifying the nearest data points (neighbors) and classifying a new data point based on the majority class of its neighbors. In this model, I set k = 5, meaning the prediction is based on the 5 closest data points.
Model Evaluation
After training the KNN model using the training dataset (X_train and y_train), I predicted the survival outcome for the test dataset using predict(). The model performance was evaluated using accuracy score, and the KNN model achieved an accuracy of approximately 70%.

####### Project Summary

In this project, I built a machine learning model to predict passenger survival on the Titanic dataset.

Steps performed:
1. Performed data cleaning by handling missing values and dropping unnecessary columns.
2. Converted categorical variables into numerical form using encoding.
3. Split the dataset into training and testing sets.
4. Applied multiple machine learning algorithms including Logistic Regression, Decision Tree, and K-Nearest Neighbors (KNN).
5. Evaluated the models using accuracy score.

Among the models tested, Logistic Regression achieved the highest accuracy of around 78%, making it the best-performing model for this dataset.

This project demonstrates the complete workflow of a machine learning classification problem, from data preprocessing to model evaluation.